version: '3'

services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-notebook
    volumes:
      - ./:/home/jovyan
    ports:
      - "8888:8888"
